name: CI
on:
  pull_request:
    branches: [ master ]
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Clippy
      run: rustup component add clippy
    - name: Build & Lint
      run: cargo clippy --verbose
